name: ignition-current
services:
  dev-current:
    image: inductiveautomation/ignition:8.1.24
    hostname: dev-current
    ports:
    - 9988:80
    volumes:
      - dev-current-data:/usr/local/bin/ignition/data
    networks:
      - dev-current
    environment:
      - IGNITION_EDITION=standar
      - GATEWAY_ADMIN_PASSWORD=password 
      - ACCEPT_IGNITION_EULA=Y
      - GATEWAY_HTTP_PORT=80
      - GATEWAY_HTTPS_PORT=443
      - DISABLE_QUICKSTART=true
    command: >
      -n dev-current-gateway
      -m 2048
  db-current:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 5533:1433
    volumes:
      - db-current-data:/var/opt/mssql
    networks:
      dev-current:
        aliases:
          - current-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Ignition#
      - MSSQL_PID=Developer
      - MSSQL_DATABASE=ignition
  smtp:
    image: dockage/mailcatcher:latest
    ports: 
      - 1080:1080
      - 1025:1025
    networks:
      dev-current:
        aliases:
          - mail-server
networks:
  dev-current:
volumes:
  dev-current-data:
  db-current-data: